spring.application.name=shopeasy

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/shopeasy_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ZzRTOEpkTThvOGE4cWcwUDRxRkpZMnM0RDdqUTdoUWY1bk41VjFnUXZXZz0=
jwt.expiration=86400000